/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package BoardGameEnvironment;
// package BoardGameEnvironment.Memory;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());


        Menu start = new Menu();
        start.run();
    }
}
